import { TrendDot, RadarConfig, DEFAULT_QUADRANTS } from "@/types";
import { megaTrends } from "./mega-trends";

export const dummyConfig: RadarConfig = {
  id: "demo-radar",
  name: "Tech Trends 2026",
  description: "Technology landscape overview",
  quadrants: DEFAULT_QUADRANTS,
  sourceWeights: {
    google_trends: 1.0,
    hackernews: 1.0,
    github: 1.0,
    arxiv: 0.7,
    news: 0.9,
    reddit: 0.8,
    stackoverflow: 0.7,
    npm_pypi: 0.6,
    producthunt: 0.5,
    wikipedia: 0.4,
  },
  dimensionWeights: {
    relevance: 0.35,
    confidence: 0.25,
    impact: 0.25,
    recency: 0.15,
  },
};

export const dummyTrends: TrendDot[] = [
  // Quadrant 0: Techniques & Patterns
  {
    id: "1",
    name: "AI Agents",
    category: "AI/ML",
    tags: ["ai", "agents", "automation"],
    relevance: 0.92,
    confidence: 0.85,
    impact: 0.95,
    timeHorizon: "short",
    ring: "adopt",
    quadrant: 0,
    signalCount: 156,
    topSources: ["hackernews", "github", "arxiv"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "2",
    name: "RAG Architectures",
    category: "AI/ML",
    tags: ["ai", "rag", "retrieval"],
    relevance: 0.88,
    confidence: 0.78,
    impact: 0.82,
    timeHorizon: "short",
    ring: "adopt",
    quadrant: 0,
    signalCount: 98,
    topSources: ["arxiv", "github", "hackernews"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "3",
    name: "Prompt Engineering",
    category: "AI/ML",
    tags: ["ai", "prompts"],
    relevance: 0.65,
    confidence: 0.9,
    impact: 0.6,
    timeHorizon: "short",
    ring: "trial",
    quadrant: 0,
    signalCount: 67,
    topSources: ["hackernews", "reddit", "news"],
    velocity: "falling",
    userOverride: false,
  },
  {
    id: "4",
    name: "Federated Learning",
    category: "AI/ML",
    tags: ["ai", "privacy", "distributed"],
    relevance: 0.35,
    confidence: 0.55,
    impact: 0.7,
    timeHorizon: "long",
    ring: "assess",
    quadrant: 0,
    signalCount: 23,
    topSources: ["arxiv", "github"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "5",
    name: "Blockchain Consensus",
    category: "Distributed Systems",
    tags: ["blockchain", "consensus"],
    relevance: 0.15,
    confidence: 0.7,
    impact: 0.3,
    timeHorizon: "long",
    ring: "hold",
    quadrant: 0,
    signalCount: 12,
    topSources: ["arxiv"],
    velocity: "falling",
    userOverride: false,
  },

  // Quadrant 1: Tools & Platforms
  {
    id: "6",
    name: "Claude / Anthropic",
    category: "AI Platforms",
    tags: ["ai", "llm", "platform"],
    relevance: 0.94,
    confidence: 0.92,
    impact: 0.93,
    timeHorizon: "short",
    ring: "adopt",
    quadrant: 1,
    signalCount: 203,
    topSources: ["hackernews", "news", "github"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "7",
    name: "Cursor / AI IDEs",
    category: "Developer Tools",
    tags: ["ai", "ide", "coding"],
    relevance: 0.82,
    confidence: 0.88,
    impact: 0.78,
    timeHorizon: "short",
    ring: "adopt",
    quadrant: 1,
    signalCount: 89,
    topSources: ["hackernews", "reddit", "producthunt"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "8",
    name: "Supabase",
    category: "Backend",
    tags: ["database", "baas", "postgres"],
    relevance: 0.7,
    confidence: 0.85,
    impact: 0.65,
    timeHorizon: "mid",
    ring: "trial",
    quadrant: 1,
    signalCount: 54,
    topSources: ["github", "hackernews", "producthunt"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "9",
    name: "Temporal.io",
    category: "Infrastructure",
    tags: ["workflow", "orchestration"],
    relevance: 0.42,
    confidence: 0.6,
    impact: 0.55,
    timeHorizon: "mid",
    ring: "assess",
    quadrant: 1,
    signalCount: 28,
    topSources: ["github", "hackernews"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "10",
    name: "Heroku",
    category: "PaaS",
    tags: ["hosting", "paas"],
    relevance: 0.12,
    confidence: 0.9,
    impact: 0.15,
    timeHorizon: "short",
    ring: "hold",
    quadrant: 1,
    signalCount: 8,
    topSources: ["stackoverflow"],
    velocity: "falling",
    userOverride: false,
  },

  // Quadrant 2: Languages & Frameworks
  {
    id: "11",
    name: "Rust",
    category: "Languages",
    tags: ["rust", "systems", "performance"],
    relevance: 0.85,
    confidence: 0.92,
    impact: 0.8,
    timeHorizon: "mid",
    ring: "adopt",
    quadrant: 2,
    signalCount: 112,
    topSources: ["github", "hackernews", "stackoverflow"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "12",
    name: "HTMX",
    category: "Frontend",
    tags: ["frontend", "html", "simplicity"],
    relevance: 0.58,
    confidence: 0.72,
    impact: 0.5,
    timeHorizon: "short",
    ring: "trial",
    quadrant: 2,
    signalCount: 45,
    topSources: ["hackernews", "github", "reddit"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "13",
    name: "Zig",
    category: "Languages",
    tags: ["zig", "systems", "low-level"],
    relevance: 0.38,
    confidence: 0.5,
    impact: 0.55,
    timeHorizon: "long",
    ring: "assess",
    quadrant: 2,
    signalCount: 31,
    topSources: ["hackernews", "github"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "14",
    name: "Svelte 5",
    category: "Frontend",
    tags: ["frontend", "svelte", "framework"],
    relevance: 0.62,
    confidence: 0.75,
    impact: 0.58,
    timeHorizon: "short",
    ring: "trial",
    quadrant: 2,
    signalCount: 52,
    topSources: ["github", "hackernews", "npm_pypi"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "15",
    name: "jQuery",
    category: "Frontend",
    tags: ["jquery", "legacy"],
    relevance: 0.08,
    confidence: 0.95,
    impact: 0.05,
    timeHorizon: "short",
    ring: "hold",
    quadrant: 2,
    signalCount: 5,
    topSources: ["stackoverflow"],
    velocity: "falling",
    userOverride: false,
  },

  // Quadrant 3: Data & Infrastructure
  {
    id: "16",
    name: "Edge Computing",
    category: "Infrastructure",
    tags: ["edge", "distributed", "latency"],
    relevance: 0.78,
    confidence: 0.7,
    impact: 0.85,
    timeHorizon: "mid",
    ring: "adopt",
    quadrant: 3,
    signalCount: 76,
    topSources: ["news", "github", "arxiv"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "17",
    name: "Vector Databases",
    category: "Data",
    tags: ["vectordb", "embeddings", "ai"],
    relevance: 0.72,
    confidence: 0.8,
    impact: 0.7,
    timeHorizon: "short",
    ring: "trial",
    quadrant: 3,
    signalCount: 63,
    topSources: ["github", "hackernews", "producthunt"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "18",
    name: "WebAssembly",
    category: "Runtime",
    tags: ["wasm", "performance", "portable"],
    relevance: 0.45,
    confidence: 0.65,
    impact: 0.72,
    timeHorizon: "mid",
    ring: "assess",
    quadrant: 3,
    signalCount: 38,
    topSources: ["github", "hackernews", "arxiv"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "19",
    name: "Quantum Computing",
    category: "Emerging",
    tags: ["quantum", "computing"],
    relevance: 0.28,
    confidence: 0.35,
    impact: 0.95,
    timeHorizon: "long",
    ring: "assess",
    quadrant: 3,
    signalCount: 19,
    topSources: ["arxiv", "news"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "20",
    name: "Hadoop MapReduce",
    category: "Data",
    tags: ["hadoop", "batch", "legacy"],
    relevance: 0.05,
    confidence: 0.92,
    impact: 0.08,
    timeHorizon: "short",
    ring: "hold",
    quadrant: 3,
    signalCount: 3,
    topSources: ["stackoverflow"],
    velocity: "falling",
    userOverride: false,
  },
  // Mega- und Makro-Trends einbinden
  ...megaTrends,
];
