import { TrendDot } from "@/types";

/**
 * Kuratierte Mega- und Makro-Trends aus autoritativen Quellen:
 *
 * Quellen:
 * - Zukunftsinstitut: 11 Megatrends (zukunftsinstitut.de/megatrends)
 * - PwC: 5 Megatrends (pwc.com/gx/en/issues/megatrends.html)
 * - EY: Megatrends 2026+ (ey.com/en_gl/megatrends)
 * - EU ESPAS: Global Trends to 2030 (ec.europa.eu/assets/epsc/pages/espas)
 * - Roland Berger: Trend Compendium 2050 (rolandberger.com)
 * - TRENDONE: Trend Universe 2026 (trendone.com)
 *
 * Confidence = Anzahl Quellen die den Trend nennen / Gesamtquellen
 * Je mehr Quellen, desto hoeher die Confidence.
 */

interface TrendSource {
  name: string;
  url: string;
}

// Sources metadata for evidence display
export const TREND_SOURCES: Record<string, TrendSource[]> = {
  // Will be referenced in detail panels
};

export const megaTrends: TrendDot[] = [
  // ═══════════════════════════════════════════════════════════════
  // MEGA-TRENDS: Langfristige transformative Kraefte
  // ═══════════════════════════════════════════════════════════════

  // ─── AI & Technologische Disruption ────────────────────────────
  // Quellen: PwC, EY, TRENDONE, Roland Berger, Zukunftsinstitut (Konnektivitaet)
  {
    id: "mega-ai-transformation",
    name: "Artificial Intelligence & Automation",
    description: "KI-Systeme automatisieren Wissensarbeit und transformieren Geschäftsmodelle in allen Branchen grundlegend.",
    category: "Mega-Trend",
    tags: ["ai", "automation", "disruption", "mega-trend",
      "PwC", "EY", "TRENDONE", "Roland Berger"],
    relevance: 0.98,
    confidence: 0.95, // 5/6 Quellen
    impact: 0.98,
    timeHorizon: "long",
    ring: "adopt",
    quadrant: 0,
    signalCount: 500,
    topSources: ["PwC", "EY", "TRENDONE", "Roland Berger"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "mega-technological-disruption",
    name: "Technological Disruption",
    description: "Neue Technologien zerstören bestehende Märkte und schaffen vollständig neue Wertschöpfungsketten.",
    category: "Mega-Trend",
    tags: ["technology", "disruption", "frontier-tech", "mega-trend",
      "PwC", "Roland Berger", "TRENDONE"],
    relevance: 0.95,
    confidence: 0.83, // 5/6
    impact: 0.95,
    timeHorizon: "long",
    ring: "adopt",
    quadrant: 0,
    signalCount: 400,
    topSources: ["PwC", "Roland Berger", "TRENDONE", "EU ESPAS"],
    velocity: "rising",
    userOverride: false,
  },

  // ─── Klimawandel & Nachhaltigkeit ─────────────────────────────
  // Quellen: PwC, EU ESPAS, Roland Berger, Zukunftsinstitut (Oekointelligenz), TRENDONE (Planet Centricity)
  {
    id: "mega-climate-sustainability",
    name: "Climate Change & Sustainability",
    description: "Klimawandel und Ressourcenknappheit zwingen Wirtschaft und Politik zu systemischer Transformation.",
    category: "Mega-Trend",
    tags: ["climate", "sustainability", "esg", "net-zero", "mega-trend",
      "PwC", "EU ESPAS", "Roland Berger", "Zukunftsinstitut", "TRENDONE"],
    relevance: 0.96,
    confidence: 1.0, // 6/6 Quellen
    impact: 0.97,
    timeHorizon: "long",
    ring: "adopt",
    quadrant: 1,
    signalCount: 450,
    topSources: ["PwC", "EU ESPAS", "Roland Berger", "Zukunftsinstitut"],
    velocity: "rising",
    userOverride: false,
  },

  // ─── Demografischer Wandel ────────────────────────────────────
  // Quellen: PwC, EU ESPAS, Roland Berger, Zukunftsinstitut
  {
    id: "mega-demographic-shift",
    name: "Demographic Shifts & Aging",
    description: "Alternde Gesellschaften, Geburtenrückgang und Migration verändern Arbeitsmärkte und Sozialsysteme strukturell.",
    category: "Mega-Trend",
    tags: ["demographics", "aging", "population", "migration", "mega-trend",
      "PwC", "EU ESPAS", "Roland Berger", "Zukunftsinstitut"],
    relevance: 0.88,
    confidence: 0.83, // 5/6
    impact: 0.9,
    timeHorizon: "long",
    ring: "adopt",
    quadrant: 1,
    signalCount: 300,
    topSources: ["PwC", "EU ESPAS", "Roland Berger", "Zukunftsinstitut"],
    velocity: "stable",
    userOverride: false,
  },

  // ─── Konnektivitaet & Digitale Vernetzung ─────────────────────
  // Quellen: Zukunftsinstitut, EU ESPAS, TRENDONE (Connected World, Data Era)
  {
    id: "mega-connectivity",
    name: "Connectivity & Digital Networks",
    description: "Allgegenwärtige digitale Vernetzung verbindet Menschen, Maschinen und Daten in Echtzeit.",
    category: "Mega-Trend",
    tags: ["connectivity", "networks", "digital", "iot", "mega-trend",
      "Zukunftsinstitut", "EU ESPAS", "TRENDONE"],
    relevance: 0.92,
    confidence: 0.83, // 5/6
    impact: 0.88,
    timeHorizon: "long",
    ring: "adopt",
    quadrant: 0,
    signalCount: 350,
    topSources: ["Zukunftsinstitut", "EU ESPAS", "TRENDONE", "Roland Berger"],
    velocity: "stable",
    userOverride: false,
  },

  // ─── Urbanisierung ────────────────────────────────────────────
  // Quellen: Zukunftsinstitut, EU ESPAS, Roland Berger, TRENDONE
  {
    id: "mega-urbanization",
    name: "Urbanization & Smart Cities",
    description: "Wachsende Städte werden zu intelligenten, vernetzten Lebensräumen der Zukunft.",
    category: "Mega-Trend",
    tags: ["urbanization", "smart-city", "infrastructure", "mega-trend",
      "Zukunftsinstitut", "EU ESPAS", "Roland Berger", "TRENDONE"],
    relevance: 0.78,
    confidence: 0.83, // 5/6
    impact: 0.82,
    timeHorizon: "long",
    ring: "adopt",
    quadrant: 3,
    signalCount: 200,
    topSources: ["Zukunftsinstitut", "EU ESPAS", "Roland Berger", "TRENDONE"],
    velocity: "stable",
    userOverride: false,
  },

  // ─── Geopolitische Fragmentierung ─────────────────────────────
  // Quellen: PwC (Fracturing World), EU ESPAS, Roland Berger, TRENDONE (Age of Disorder)
  {
    id: "mega-geopolitical-fracturing",
    name: "Geopolitical Fragmentation",
    description: "Die Weltordnung zerfällt in konkurrierende Machtblöcke mit eigenständigen Technologie- und Handelsräumen.",
    category: "Mega-Trend",
    tags: ["geopolitics", "fragmentation", "multipolar", "mega-trend",
      "PwC", "EU ESPAS", "Roland Berger", "TRENDONE", "World Monitor"],
    relevance: 0.85,
    confidence: 0.83, // 5/6
    impact: 0.88,
    timeHorizon: "long",
    ring: "adopt",
    quadrant: 1,
    signalCount: 250,
    topSources: ["PwC", "EU ESPAS", "Roland Berger", "TRENDONE"],
    velocity: "rising",
    userOverride: false,
  },

  // ─── Future of Work ───────────────────────────────────────────
  // Quellen: Zukunftsinstitut, EY, TRENDONE (Future Skillsets), Roland Berger
  {
    id: "mega-future-of-work",
    name: "Future of Work",
    description: "Automatisierung und neue Arbeitsmodelle definieren Qualifikationen, Karrieren und Organisationen neu.",
    category: "Mega-Trend",
    tags: ["work", "skills", "remote", "automation", "mega-trend",
      "Zukunftsinstitut", "EY", "TRENDONE", "Roland Berger"],
    relevance: 0.88,
    confidence: 0.83, // 5/6
    impact: 0.85,
    timeHorizon: "long",
    ring: "adopt",
    quadrant: 1,
    signalCount: 280,
    topSources: ["Zukunftsinstitut", "EY", "TRENDONE", "Roland Berger"],
    velocity: "stable",
    userOverride: false,
  },

  // ─── Gesundheit & Biotech ─────────────────────────────────────
  // Quellen: Zukunftsinstitut (Gesundheit), Roland Berger (Health & Care), TRENDONE (Healthstyle)
  {
    id: "mega-health-biotech",
    name: "Health, Biotech & Longevity",
    description: "Biotechnologie und Präzisionsmedizin verschieben den Fokus von Behandlung zu Prävention und Lebensverlängerung.",
    category: "Mega-Trend",
    tags: ["health", "biotech", "longevity", "genomics", "mega-trend",
      "Zukunftsinstitut", "Roland Berger", "TRENDONE"],
    relevance: 0.85,
    confidence: 0.67, // 4/6
    impact: 0.92,
    timeHorizon: "long",
    ring: "adopt",
    quadrant: 1,
    signalCount: 220,
    topSources: ["Zukunftsinstitut", "Roland Berger", "TRENDONE"],
    velocity: "rising",
    userOverride: false,
  },

  // ─── Sicherheit & Vertrauen ───────────────────────────────────
  // Quellen: Zukunftsinstitut (Sicherheit), EY (Trust Economy), PwC (Social Instability)
  {
    id: "mega-security-trust",
    name: "Security, Trust & Resilience",
    description: "Zunehmende Bedrohungen durch Cyberangriffe und gesellschaftliche Spannungen erfordern neue Resilienzstrategien.",
    category: "Mega-Trend",
    tags: ["security", "trust", "resilience", "cyber", "mega-trend",
      "Zukunftsinstitut", "EY", "PwC", "World Monitor"],
    relevance: 0.82,
    confidence: 0.67, // 4/6
    impact: 0.85,
    timeHorizon: "long",
    ring: "adopt",
    quadrant: 0,
    signalCount: 200,
    topSources: ["Zukunftsinstitut", "EY", "PwC"],
    velocity: "rising",
    userOverride: false,
  },

  // ─── Soziale Instabilitaet & Ungleichheit ─────────────────────
  // Quellen: PwC (Social Instability), TRENDONE (Caring Society), Roland Berger
  {
    id: "mega-social-instability",
    name: "Social Instability & Inequality",
    description: "Wachsende Ungleichheit und politische Polarisierung destabilisieren gesellschaftliche Grundstrukturen.",
    category: "Mega-Trend",
    tags: ["social", "inequality", "polarization", "mega-trend",
      "PwC", "TRENDONE", "Roland Berger", "World Monitor"],
    relevance: 0.78,
    confidence: 0.67, // 4/6
    impact: 0.82,
    timeHorizon: "long",
    ring: "trial",
    quadrant: 1,
    signalCount: 150,
    topSources: ["PwC", "TRENDONE", "Roland Berger"],
    velocity: "rising",
    userOverride: false,
  },

  // ─── Energie-Transformation ───────────────────────────────────
  // Quellen: EU ESPAS, Roland Berger, PwC (Climate), TRENDONE (Planet Centricity)
  {
    id: "mega-energy-transition",
    name: "Energy Transition & Decarbonization",
    description: "Die Abkehr von fossilen Brennstoffen beschleunigt sich durch Technologiekosten und politischen Druck.",
    category: "Mega-Trend",
    tags: ["energy", "renewable", "decarbonization", "transition", "mega-trend",
      "EU ESPAS", "Roland Berger", "PwC", "World Monitor"],
    relevance: 0.9,
    confidence: 0.83, // 5/6
    impact: 0.92,
    timeHorizon: "long",
    ring: "adopt",
    quadrant: 3,
    signalCount: 280,
    topSources: ["EU ESPAS", "Roland Berger", "PwC", "TRENDONE"],
    velocity: "rising",
    userOverride: false,
  },

  // ─── Wissenskultur & Bildung ──────────────────────────────────
  // Quellen: Zukunftsinstitut (Wissenskultur), TRENDONE (Future Skillsets), Roland Berger (Education)
  {
    id: "mega-knowledge-culture",
    name: "Knowledge Culture & Lifelong Learning",
    description: "Lebenslanges Lernen wird zur Kernkompetenz in einer Wissensgesellschaft mit rasantem Wandel.",
    category: "Mega-Trend",
    tags: ["knowledge", "education", "learning", "skills", "mega-trend",
      "Zukunftsinstitut", "TRENDONE", "Roland Berger"],
    relevance: 0.72,
    confidence: 0.5, // 3/6
    impact: 0.75,
    timeHorizon: "long",
    ring: "trial",
    quadrant: 1,
    signalCount: 120,
    topSources: ["Zukunftsinstitut", "TRENDONE", "Roland Berger"],
    velocity: "stable",
    userOverride: false,
  },

  // ─── Mobilitaet ───────────────────────────────────────────────
  // Quellen: Zukunftsinstitut (Mobilitaet), TRENDONE (Intelligent Infrastructure), Roland Berger
  {
    id: "mega-mobility",
    name: "Mobility & Autonomous Transport",
    description: "Autonome Fahrzeuge, Elektromobilität und Shared Mobility gestalten urbane und ländliche Mobilität um.",
    category: "Mega-Trend",
    tags: ["mobility", "autonomous", "transport", "ev", "mega-trend",
      "Zukunftsinstitut", "TRENDONE", "Roland Berger"],
    relevance: 0.75,
    confidence: 0.5, // 3/6
    impact: 0.8,
    timeHorizon: "mid",
    ring: "trial",
    quadrant: 3,
    signalCount: 140,
    topSources: ["Zukunftsinstitut", "TRENDONE", "Roland Berger"],
    velocity: "stable",
    userOverride: false,
  },

  // ─── Identitaet & Wertewandel ─────────────────────────────────
  // Quellen: Zukunftsinstitut (Identitaetsdynamik), Roland Berger (Values), TRENDONE (Evolving Consumerism)
  {
    id: "mega-identity-values",
    name: "Identity Dynamics & Value Shifts",
    description: "Individualisierung und Wertewandel führen zu neuen Lebensentwürfen und gesellschaftlichen Spaltungen.",
    category: "Mega-Trend",
    tags: ["identity", "values", "diversity", "lifestyle", "mega-trend",
      "Zukunftsinstitut", "Roland Berger", "TRENDONE"],
    relevance: 0.65,
    confidence: 0.5, // 3/6
    impact: 0.7,
    timeHorizon: "long",
    ring: "trial",
    quadrant: 1,
    signalCount: 90,
    topSources: ["Zukunftsinstitut", "Roland Berger", "TRENDONE"],
    velocity: "stable",
    userOverride: false,
  },

  // ═══════════════════════════════════════════════════════════════
  // MAKRO-TRENDS: Mittelfristige Entwicklungen
  // ═══════════════════════════════════════════════════════════════

  // ─── AI Makro-Trends ──────────────────────────────────────────
  {
    id: "macro-generative-ai",
    name: "Generative AI & Foundation Models",
    description: "Large Language Models und Bildgeneratoren machen kreative und analytische KI-Fähigkeiten allgemein zugänglich.",
    category: "Makro-Trend",
    tags: ["ai", "generative", "llm", "foundation-models", "makro-trend",
      "EY", "TRENDONE"],
    relevance: 0.96,
    confidence: 0.85,
    impact: 0.95,
    timeHorizon: "short",
    ring: "adopt",
    quadrant: 0,
    signalCount: 420,
    topSources: ["EY", "TRENDONE", "hackernews", "github"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "macro-ai-agents",
    name: "AI Agents & Autonomous Systems",
    description: "Autonome KI-Systeme übernehmen komplexe Aufgaben selbstständig und arbeiten ohne menschliche Steuerung.",
    category: "Makro-Trend",
    tags: ["ai", "agents", "autonomous", "makro-trend", "EY"],
    relevance: 0.92,
    confidence: 0.78,
    impact: 0.9,
    timeHorizon: "short",
    ring: "adopt",
    quadrant: 0,
    signalCount: 180,
    topSources: ["EY", "hackernews", "github", "arxiv"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "macro-human-machine",
    name: "Human-Machine Collaboration",
    description: "Mensch und Maschine arbeiten ergänzend zusammen — KI verstärkt menschliche Fähigkeiten statt sie zu ersetzen.",
    category: "Makro-Trend",
    tags: ["human-machine", "augmentation", "cobots", "makro-trend",
      "EY", "Roland Berger"],
    relevance: 0.82,
    confidence: 0.72,
    impact: 0.85,
    timeHorizon: "mid",
    ring: "adopt",
    quadrant: 0,
    signalCount: 130,
    topSources: ["EY", "Roland Berger", "TRENDONE"],
    velocity: "rising",
    userOverride: false,
  },

  // ─── Nachhaltigkeit Makro-Trends ──────────────────────────────
  {
    id: "macro-green-energy",
    name: "Renewable Energy & Green Tech",
    description: "Solar, Wind und Wasserstoff werden zur günstigsten und dominanten Energieversorgung weltweit.",
    category: "Makro-Trend",
    tags: ["renewable", "solar", "wind", "hydrogen", "makro-trend",
      "Roland Berger", "EU ESPAS"],
    relevance: 0.88,
    confidence: 0.82,
    impact: 0.9,
    timeHorizon: "mid",
    ring: "adopt",
    quadrant: 3,
    signalCount: 200,
    topSources: ["Roland Berger", "EU ESPAS", "PwC"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "macro-circular-economy",
    name: "Circular Economy",
    description: "Produkte werden konsequent wiederverwendet, repariert und recycelt — Abfall wird zum Rohstoff.",
    category: "Makro-Trend",
    tags: ["circular", "recycling", "waste", "makro-trend",
      "TRENDONE", "Roland Berger"],
    relevance: 0.62,
    confidence: 0.55,
    impact: 0.72,
    timeHorizon: "mid",
    ring: "trial",
    quadrant: 1,
    signalCount: 65,
    topSources: ["TRENDONE", "Roland Berger", "EU ESPAS"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "macro-conscious-consumption",
    name: "Conscious Consumption & Eating",
    description: "Verbraucher fordern nachhaltige, ethisch produzierte Produkte und hinterfragen ihren ökologischen Fußabdruck.",
    category: "Makro-Trend",
    tags: ["conscious", "consumption", "food", "sustainability", "makro-trend",
      "TRENDONE"],
    relevance: 0.55,
    confidence: 0.5,
    impact: 0.6,
    timeHorizon: "mid",
    ring: "assess",
    quadrant: 1,
    signalCount: 45,
    topSources: ["TRENDONE", "Zukunftsinstitut"],
    velocity: "stable",
    userOverride: false,
  },

  // ─── Digitale Infrastruktur Makro-Trends ──────────────────────
  {
    id: "macro-cloud-native",
    name: "Cloud Native & Multi-Cloud",
    description: "Anwendungen werden direkt für die Cloud gebaut — skalierbar, resilient und ohne eigene Infrastruktur.",
    category: "Makro-Trend",
    tags: ["cloud", "kubernetes", "infrastructure", "makro-trend"],
    relevance: 0.85,
    confidence: 0.82,
    impact: 0.78,
    timeHorizon: "short",
    ring: "adopt",
    quadrant: 2,
    signalCount: 200,
    topSources: ["github", "hackernews", "stackoverflow"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "macro-edge-iot",
    name: "Edge Computing & IoT",
    description: "Datenverarbeitung verlagert sich an den Rand des Netzwerks — direkt dort, wo Daten entstehen.",
    category: "Makro-Trend",
    tags: ["edge", "iot", "distributed", "makro-trend",
      "TRENDONE", "EU ESPAS"],
    relevance: 0.72,
    confidence: 0.68,
    impact: 0.78,
    timeHorizon: "mid",
    ring: "trial",
    quadrant: 3,
    signalCount: 85,
    topSources: ["TRENDONE", "EU ESPAS", "Roland Berger"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "macro-data-economy",
    name: "Data Economy & Data Sovereignty",
    description: "Daten werden zur strategischen Ressource, während Kontrolle über Datensouveränität zum Wettbewerbsvorteil wird.",
    category: "Makro-Trend",
    tags: ["data", "sovereignty", "privacy", "gdpr", "makro-trend",
      "TRENDONE", "EU ESPAS"],
    relevance: 0.78,
    confidence: 0.72,
    impact: 0.8,
    timeHorizon: "mid",
    ring: "adopt",
    quadrant: 3,
    signalCount: 120,
    topSources: ["TRENDONE", "EU ESPAS", "Roland Berger"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "macro-cybersecurity",
    name: "Cybersecurity & Zero Trust",
    description: "Zero-Trust-Architekturen und KI-gestützte Erkennung sind Reaktion auf zunehmende Cyberbedrohungen.",
    category: "Makro-Trend",
    tags: ["cybersecurity", "zero-trust", "ransomware", "makro-trend"],
    relevance: 0.82,
    confidence: 0.8,
    impact: 0.82,
    timeHorizon: "short",
    ring: "adopt",
    quadrant: 0,
    signalCount: 150,
    topSources: ["hackernews", "news", "PwC"],
    velocity: "rising",
    userOverride: false,
  },

  // ─── Arbeit & Gesellschaft Makro-Trends ───────────────────────
  {
    id: "macro-remote-hybrid",
    name: "Remote & Hybrid Work",
    description: "Hybrides Arbeiten zwischen Büro und Homeoffice etabliert sich als neuer Arbeitsstandard.",
    category: "Makro-Trend",
    tags: ["remote", "hybrid", "collaboration", "makro-trend",
      "Zukunftsinstitut"],
    relevance: 0.72,
    confidence: 0.85,
    impact: 0.68,
    timeHorizon: "short",
    ring: "adopt",
    quadrant: 1,
    signalCount: 120,
    topSources: ["Zukunftsinstitut", "news", "reddit"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "macro-skills-upskilling",
    name: "Skills Gap & Upskilling",
    description: "Automatisierung schafft Qualifikationslücken, die nur durch kontinuierliche Weiterbildung geschlossen werden können.",
    category: "Makro-Trend",
    tags: ["skills", "upskilling", "education", "makro-trend",
      "TRENDONE", "Roland Berger"],
    relevance: 0.7,
    confidence: 0.72,
    impact: 0.72,
    timeHorizon: "mid",
    ring: "trial",
    quadrant: 1,
    signalCount: 75,
    topSources: ["TRENDONE", "Roland Berger", "Zukunftsinstitut"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "macro-attention-economy",
    name: "Attention Economy & Creator Platforms",
    description: "Plattformen konkurrieren um menschliche Aufmerksamkeit — Creator Economy wächst zur eigenständigen Wirtschaftsform.",
    category: "Makro-Trend",
    tags: ["attention", "creator", "content", "platform", "makro-trend",
      "TRENDONE"],
    relevance: 0.65,
    confidence: 0.6,
    impact: 0.62,
    timeHorizon: "short",
    ring: "trial",
    quadrant: 1,
    signalCount: 55,
    topSources: ["TRENDONE", "producthunt", "reddit"],
    velocity: "stable",
    userOverride: false,
  },

  // ─── Gesundheit Makro-Trends ──────────────────────────────────
  {
    id: "macro-digital-health",
    name: "Digital Health & Telemedicine",
    description: "Telemedizin, Wearables und KI-Diagnostik verlagern Gesundheitsversorgung ins Digitale und nach Hause.",
    category: "Makro-Trend",
    tags: ["telehealth", "digital-health", "wearables", "makro-trend",
      "TRENDONE", "Roland Berger"],
    relevance: 0.72,
    confidence: 0.72,
    impact: 0.75,
    timeHorizon: "short",
    ring: "trial",
    quadrant: 1,
    signalCount: 80,
    topSources: ["TRENDONE", "Roland Berger", "news"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "macro-genomics",
    name: "Genomics & Personalized Medicine",
    description: "Genomsequenzierung und CRISPR ermöglichen personalisierte Therapien und präventive Medizin auf Genebene.",
    category: "Makro-Trend",
    tags: ["genomics", "crispr", "personalized", "makro-trend",
      "TRENDONE", "Roland Berger"],
    relevance: 0.55,
    confidence: 0.6,
    impact: 0.85,
    timeHorizon: "long",
    ring: "assess",
    quadrant: 1,
    signalCount: 42,
    topSources: ["TRENDONE", "Roland Berger", "arxiv"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "macro-engineered-evolution",
    name: "Engineered Evolution & Human Enhancement",
    description: "Biotechnologie und Neurotechnologie beginnen, menschliche kognitive und physische Fähigkeiten gezielt zu erweitern.",
    category: "Makro-Trend",
    tags: ["biotech", "enhancement", "neurotechnology", "makro-trend",
      "TRENDONE", "EY"],
    relevance: 0.42,
    confidence: 0.45,
    impact: 0.82,
    timeHorizon: "long",
    ring: "assess",
    quadrant: 0,
    signalCount: 30,
    topSources: ["TRENDONE", "EY", "arxiv"],
    velocity: "stable",
    userOverride: false,
  },

  // ─── Emerging Tech Makro-Trends ───────────────────────────────
  {
    id: "macro-quantum-computing",
    name: "Quantum Computing",
    description: "Quantencomputer versprechen exponentiell schnellere Berechnungen — mit disruptivem Potenzial für Kryptographie und Simulation.",
    category: "Makro-Trend",
    tags: ["quantum", "computing", "post-quantum", "makro-trend",
      "Roland Berger"],
    relevance: 0.42,
    confidence: 0.45,
    impact: 0.92,
    timeHorizon: "long",
    ring: "assess",
    quadrant: 0,
    signalCount: 50,
    topSources: ["Roland Berger", "arxiv", "news"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "macro-spatial-computing",
    name: "Spatial Computing & XR",
    description: "AR/VR und räumliche Interfaces schaffen immersive digitale Erfahrungen jenseits flacher Bildschirme.",
    category: "Makro-Trend",
    tags: ["xr", "ar", "vr", "spatial", "metaverse", "makro-trend",
      "TRENDONE"],
    relevance: 0.58,
    confidence: 0.55,
    impact: 0.7,
    timeHorizon: "mid",
    ring: "assess",
    quadrant: 0,
    signalCount: 60,
    topSources: ["TRENDONE", "news", "hackernews"],
    velocity: "rising",
    userOverride: false,
  },
  {
    id: "macro-web3-decentralization",
    name: "Web3 & Decentralization",
    description: "Blockchain-basierte Dezentralisierung verliert an Dynamik — praktische Anwendungsfälle bleiben überschaubar.",
    category: "Makro-Trend",
    tags: ["web3", "blockchain", "decentralized", "makro-trend"],
    relevance: 0.38,
    confidence: 0.45,
    impact: 0.55,
    timeHorizon: "long",
    ring: "hold",
    quadrant: 0,
    signalCount: 35,
    topSources: ["hackernews", "reddit"],
    velocity: "falling",
    userOverride: false,
  },

  // ─── Commerce & Business Makro-Trends ─────────────────────────
  {
    id: "macro-seamless-commerce",
    name: "Seamless & Omnichannel Commerce",
    description: "Nahtlose Kauferlebnisse über alle Kanäle hinweg werden zur Grunderwartung der Konsumenten.",
    category: "Makro-Trend",
    tags: ["commerce", "omnichannel", "retail", "makro-trend",
      "TRENDONE"],
    relevance: 0.6,
    confidence: 0.55,
    impact: 0.62,
    timeHorizon: "short",
    ring: "trial",
    quadrant: 1,
    signalCount: 50,
    topSources: ["TRENDONE", "producthunt", "news"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "macro-platform-economy",
    name: "Platform Economy & Ecosystems",
    description: "Digitale Plattformen dominieren als Intermediäre — Ökosystem-Denken verdrängt Produktdenken.",
    category: "Makro-Trend",
    tags: ["platform", "ecosystem", "api", "makro-trend",
      "Roland Berger"],
    relevance: 0.75,
    confidence: 0.72,
    impact: 0.78,
    timeHorizon: "mid",
    ring: "adopt",
    quadrant: 1,
    signalCount: 110,
    topSources: ["Roland Berger", "hackernews", "news"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "macro-autonomous-mobility",
    name: "Autonomous Mobility & EVs",
    description: "Selbstfahrende Fahrzeuge und Elektromobilität transformieren Personen- und Güterverkehr grundlegend.",
    category: "Makro-Trend",
    tags: ["autonomous", "ev", "self-driving", "mobility", "makro-trend",
      "Zukunftsinstitut", "Roland Berger"],
    relevance: 0.68,
    confidence: 0.62,
    impact: 0.82,
    timeHorizon: "mid",
    ring: "trial",
    quadrant: 3,
    signalCount: 75,
    topSources: ["Zukunftsinstitut", "Roland Berger", "news"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "macro-exponential-manufacturing",
    name: "Exponential Manufacturing & 3D Printing",
    description: "3D-Druck und digitale Fertigung machen Produktion dezentraler, schneller und individualisierbarer.",
    category: "Makro-Trend",
    tags: ["3d-printing", "manufacturing", "additive", "makro-trend",
      "TRENDONE"],
    relevance: 0.48,
    confidence: 0.52,
    impact: 0.65,
    timeHorizon: "mid",
    ring: "assess",
    quadrant: 2,
    signalCount: 38,
    topSources: ["TRENDONE", "arxiv", "github"],
    velocity: "stable",
    userOverride: false,
  },
  {
    id: "macro-smart-surroundings",
    name: "Smart Surroundings & Ambient Intelligence",
    description: "Intelligente Umgebungen mit Sensoren und ambientem Computing reagieren proaktiv auf menschliche Bedürfnisse.",
    category: "Makro-Trend",
    tags: ["smart-home", "ambient", "sensors", "makro-trend",
      "TRENDONE"],
    relevance: 0.52,
    confidence: 0.55,
    impact: 0.6,
    timeHorizon: "mid",
    ring: "assess",
    quadrant: 3,
    signalCount: 42,
    topSources: ["TRENDONE", "producthunt"],
    velocity: "stable",
    userOverride: false,
  },
];

/**
 * Get unique categories from mega trends
 */
export function getMegaTrendCategories(): string[] {
  return [...new Set(megaTrends.map((t) => t.category))].sort();
}
