/**
 * PLANNED_CONNECTORS — Roadmap of data sources that are scoped for
 * integration but not yet wired up as live connectors.
 *
 * Source of truth: the Notion database "🔌 SIS — Datenquellen & APIs".
 * The QuellenTable reads this list alongside the live `connectors` array
 * and shows each entry with a status badge ("GEPLANT" for active roadmap,
 * "BACKLOG" for deferred work that needs dedicated setup).
 *
 * Entries also carry an `access` field that drives the auth/key badge:
 *   - "no-auth"       → Can be built directly by the framework
 *   - "free-key"      → Needs a free API key (user must register)
 *   - "free-signup"   → Needs a free account + OAuth/token
 *   - "download"      → Bulk download only, no live API
 *   - "commercial"    → Paid tier required
 *   - "open-source"   → Open-source API (may be self-hosted)
 *   - "public-scrape" → Public website, needs scraping layer
 *
 * When a planned connector gets built:
 *   1. Create `src/connectors/<slug>.ts` (use buildDeclarativeConnector)
 *   2. Register it in `src/connectors/index.ts`
 *   3. Remove its entry from this file
 *   4. Flip "Bereits integriert" in the Notion database
 */

import type { CategoryKey } from "./source-taxonomy";

export type PlannedConnectorPriority = "high" | "medium" | "low";
export type PlannedConnectorAccess =
  | "no-auth"
  | "free-key"
  | "free-signup"
  | "download"
  | "commercial"
  | "open-source"
  | "public-scrape";

/**
 * Category keys a planned connector can carry. These are the fine-grain
 * domain categories from source-taxonomy.ts minus the two pseudo keys
 * "all" and "forschung" (no connector lives in either pseudo bucket).
 */
export type PlannedConnectorCategory = Exclude<CategoryKey, "all" | "forschung">;

/** Matches the TypeBadgeKind shape used by VoltTypeBadge. */
export type PlannedConnectorType = "live-signal" | "social" | "forschung" | "prognose";

export interface PlannedConnector {
  slug: string;
  displayName: string;
  category: PlannedConnectorCategory;
  type: PlannedConnectorType;
  priority: PlannedConnectorPriority;
  access: PlannedConnectorAccess;
  descriptionDe: string;
  descriptionEn: string;
  docUrl: string;
  apiUrl?: string;
  rateLimit?: string;
  notionUrl: string;
  /** True = not scheduled for the next waves of work. Rendered as "BACKLOG". */
  backlog?: boolean;
  /** True = needs a user-provided API key before it can be wired up. */
  needsKey?: boolean;
}

export const PLANNED_CONNECTORS: PlannedConnector[] = [
  {
    slug: "bundestag-dip",
    displayName: "Bundestag DIP API",
    category: "recht",
    type: "live-signal",
    priority: "high",
    access: "free-key",
    descriptionDe: "Deutsche Drucksachen, Plenarprotokolle, Abstimmungen. Themen-Tracking, Gesetzgebungsvolumen.",
    descriptionEn: "Deutsche Drucksachen, Plenarprotokolle, Abstimmungen. Themen-Tracking, Gesetzgebungsvolumen.",
    docUrl: "https://dip.bundestag.de/%C3%BCber-dip/hilfe/api",
    apiUrl: "https://search.dip.bundestag.de/api/v1",
    notionUrl: "https://www.notion.so/37d5a5bfc1d541959228bf7c0b8f649a",
    needsKey: true,
  },
  {
    slug: "entso-e-transparency-platform",
    displayName: "ENTSO-E Transparency Platform",
    category: "energie",
    type: "live-signal",
    priority: "high",
    access: "free-signup",
    descriptionDe: "Europäisches Stromnetz: Erzeugungsmix, Preise, grenzüberschreitende Flüsse. 15-Min-Auflösung. Erneuerbaren-Anteil in Echtzeit als Transition-Tracker.",
    descriptionEn: "Europäisches Stromnetz: Erzeugungsmix, Preise, grenzüberschreitende Flüsse. 15-Min-Auflösung. Erneuerbaren-Anteil in Echtzeit als Transition-Tracker.",
    docUrl: "https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html",
    apiUrl: "https://web-api.tp.entsoe.eu/api",
    rateLimit: "400 Req/Min",
    notionUrl: "https://www.notion.so/5f228688e41a42538d8a20267e52ef07",
    needsKey: true,
  },
  {
    slug: "eur-lex-cellar",
    displayName: "EUR-Lex / CELLAR API",
    category: "recht",
    type: "live-signal",
    priority: "high",
    access: "no-auth",
    descriptionDe: "EU-Gesetzgebung maschinenlesbar. Verordnungen, Richtlinien, Konsultationen. Policy-Frühindikator.",
    descriptionEn: "EU-Gesetzgebung maschinenlesbar. Verordnungen, Richtlinien, Konsultationen. Policy-Frühindikator.",
    docUrl: "https://op.europa.eu/en/web/cellar",
    apiUrl: "https://publications.europa.eu/webapi/rdf/sparql",
    notionUrl: "https://www.notion.so/0eee98d473ad4c21a967bbeaf1f94738",
  },
  {
    slug: "fao-faostat",
    displayName: "FAO FAOSTAT API",
    category: "agrar",
    type: "live-signal",
    priority: "high",
    access: "free-key",
    descriptionDe: "Globale Produktion, Handel, Preise, Hunger-Indikatoren. FAO Food Price Index = Instabilitäts-Frühindikator #1. Öffentliche JSON-Endpoints sind gatet (Missing Authorization Header) oder timen aus — nur Bulk-CSV ist public. Braucht FAO-Registration.",
    descriptionEn: "Globale Produktion, Handel, Preise, Hunger-Indikatoren. FAO Food Price Index = Instabilitäts-Frühindikator #1. Öffentliche JSON-Endpoints sind gatet (Missing Authorization Header) oder timen aus — nur Bulk-CSV ist public. Braucht FAO-Registration.",
    docUrl: "https://faostat.fao.org/api-access",
    apiUrl: "https://fenixservices.fao.org/faostat/api/v1",
    notionUrl: "https://www.notion.so/b2ca39ac1659452198da7dc17a110841",
    needsKey: true,
  },
  // google-books-ngram-viewer: moved to live-connectors (bonus sprint 2026-04-09)
  {
    slug: "lastfm",
    displayName: "Last.fm API",
    category: "kultur",
    type: "live-signal",
    priority: "high",
    access: "free-key",
    descriptionDe: "Tag-Trends + Charts als Musik-Kulturbarometer. Längste kontinuierliche Hördaten-Historie seit 2002.",
    descriptionEn: "Tag-Trends + Charts als Musik-Kulturbarometer. Längste kontinuierliche Hördaten-Historie seit 2002.",
    docUrl: "https://last.fm/api",
    apiUrl: "https://ws.audioscrobbler.com/2.0",
    notionUrl: "https://www.notion.so/f9f8bb2a885a481486616d9b03711884",
    needsKey: true,
  },
  {
    slug: "nist-nvd-api-cve-datenbank",
    displayName: "NIST NVD API (CVE-Datenbank)",
    category: "cyber",
    type: "live-signal",
    priority: "high",
    access: "free-key",
    descriptionDe: "CVE-Volumen nach Schweregrad als Tech-Risiko-Signal, Zero-Day-Trends.",
    descriptionEn: "CVE-Volumen nach Schweregrad als Tech-Risiko-Signal, Zero-Day-Trends.",
    docUrl: "https://nvd.nist.gov/developers",
    apiUrl: "https://services.nvd.nist.gov/rest/json/cves/2.0",
    rateLimit: "50 Req/30s (mit Key)",
    notionUrl: "https://www.notion.so/65368564b8a945b3b8f9950f54c63443",
    needsKey: true,
  },
  {
    slug: "omdb-api-ratings-aggregator",
    displayName: "OMDb API (Ratings-Aggregator)",
    category: "kultur",
    type: "live-signal",
    priority: "high",
    access: "free-key",
    descriptionDe: "IMDb + Rotten Tomatoes + Metacritic in einem Call. Kritiker-Publikum-Divergenz messbar.",
    descriptionEn: "IMDb + Rotten Tomatoes + Metacritic in einem Call. Kritiker-Publikum-Divergenz messbar.",
    docUrl: "https://omdbapi.com",
    apiUrl: "https://omdbapi.com",
    rateLimit: "1.000 Req/Tag (Free)",
    notionUrl: "https://www.notion.so/86b6761e37204558a5a9017680ac1209",
    needsKey: true,
  },
  {
    slug: "steam-web",
    displayName: "Steam Web API",
    category: "gaming",
    type: "live-signal",
    priority: "high",
    access: "free-key",
    descriptionDe: "Concurrent Players als Echtzeit-Adoption-Signal. Spikes = kulturelle Events.",
    descriptionEn: "Concurrent Players als Echtzeit-Adoption-Signal. Spikes = kulturelle Events.",
    docUrl: "https://developer.valvesoftware.com/wiki/Steam_Web_API",
    apiUrl: "https://api.steampowered.com",
    notionUrl: "https://www.notion.so/b83fe0868b5e4939a525381980db06e1",
    needsKey: true,
  },
  // steamspy: moved to live-connectors (bonus sprint 2026-04-09)
  {
    slug: "the-odds",
    displayName: "The Odds API",
    category: "wetten",
    type: "prognose",
    priority: "high",
    access: "free-key",
    descriptionDe: "Aggregierte Quoten von 70+ Bookmakers. Historische Quoten ab 2020. Quotenverschiebungen als Erwartungs-Signal.",
    descriptionEn: "Aggregierte Quoten von 70+ Bookmakers. Historische Quoten ab 2020. Quotenverschiebungen als Erwartungs-Signal.",
    docUrl: "https://the-odds-api.com/liveapi/guides/v4",
    apiUrl: "https://api.the-odds-api.com/v4/sports",
    rateLimit: "500 Credits/Monat (Free)",
    notionUrl: "https://www.notion.so/5a1817c48c834cbd9cd245c77a3dc3f4",
    needsKey: true,
  },
  {
    slug: "tmdb-api-the-movie-database",
    displayName: "TMDB API (The Movie Database)",
    category: "kultur",
    type: "live-signal",
    priority: "high",
    access: "free-key",
    descriptionDe: "Trending Filme/Serien + Keywords + Votes = kultureller Stimmungsindikator. Genre-Trends über Zeit trackbar.",
    descriptionEn: "Trending Filme/Serien + Keywords + Votes = kultureller Stimmungsindikator. Genre-Trends über Zeit trackbar.",
    docUrl: "https://developer.themoviedb.org",
    apiUrl: "https://api.themoviedb.org/3",
    notionUrl: "https://www.notion.so/5994bd4cf7a84306b65c5fd6c7773eac",
    needsKey: true,
  },
  {
    slug: "tor-metrics",
    displayName: "Tor Metrics",
    category: "cyber",
    type: "live-signal",
    priority: "high",
    access: "no-auth",
    descriptionDe: "Tor-Nutzung pro Land als Zensur-/Freiheits-Indikator. Spikes korrelieren mit politischer Repression.",
    descriptionEn: "Tor-Nutzung pro Land als Zensur-/Freiheits-Indikator. Spikes korrelieren mit politischer Repression.",
    docUrl: "https://metrics.torproject.org",
    apiUrl: "https://metrics.torproject.org/userstats-relay-country.csv",
    notionUrl: "https://www.notion.so/ec3f59da18324d41b736820add90f38e",
  },
  {
    slug: "trakt",
    displayName: "Trakt API",
    category: "kultur",
    type: "live-signal",
    priority: "high",
    access: "free-key",
    descriptionDe: "Community-Sehgewohnheiten, Trending Shows/Movies, Scrobbling. Ratings-Verteilung als emotionales Signal.",
    descriptionEn: "Community-Sehgewohnheiten, Trending Shows/Movies, Scrobbling. Ratings-Verteilung als emotionales Signal.",
    docUrl: "https://trakt.docs.apiary.io",
    apiUrl: "https://api.trakt.tv",
    notionUrl: "https://www.notion.so/d39a7390667744b696123e7ce3877aed",
    needsKey: true,
  },
  {
    slug: "twitch",
    displayName: "Twitch API",
    category: "gaming",
    type: "live-signal",
    priority: "high",
    access: "free-signup",
    descriptionDe: "Top Games + Viewer-Zahlen = Live-Kulturbarometer. Kategorie-Shifts als Wandel der Streaming-Kultur.",
    descriptionEn: "Top Games + Viewer-Zahlen = Live-Kulturbarometer. Kategorie-Shifts als Wandel der Streaming-Kultur.",
    docUrl: "https://dev.twitch.tv/docs/api",
    apiUrl: "https://api.twitch.tv/helix",
    rateLimit: "800 Req/Min",
    notionUrl: "https://www.notion.so/c37c17ad5ed54c41b35ff385434d66a8",
    needsKey: true,
  },
  {
    slug: "un-comtrade",
    displayName: "UN Comtrade API",
    category: "supply",
    type: "live-signal",
    priority: "high",
    access: "free-key",
    descriptionDe: "Bilaterale Handelsströme als Geopolitik-Signal. 200+ Länder, HS-Codes.",
    descriptionEn: "Bilaterale Handelsströme als Geopolitik-Signal. 200+ Länder, HS-Codes.",
    docUrl: "https://comtrade.un.org/data/dev/portal",
    apiUrl: "https://comtradeapi.un.org/data/v1/get",
    rateLimit: "100 Req/Stunde (Free)",
    notionUrl: "https://www.notion.so/b4bfe1bbf52e44a9a9219f7758fe0ab9",
    needsKey: true,
  },
  {
    slug: "betfair-exchange",
    displayName: "Betfair Exchange API",
    category: "wetten",
    type: "prognose",
    priority: "medium",
    access: "free-signup",
    descriptionDe: "Schärfste Quoten (Peer-to-Peer). Politik-Märkte in UK/EU besonders wertvoll.",
    descriptionEn: "Schärfste Quoten (Peer-to-Peer). Politik-Märkte in UK/EU besonders wertvoll.",
    docUrl: "https://developer.betfair.com",
    apiUrl: "https://api.betfair.com/exchange",
    notionUrl: "https://www.notion.so/5335650abb854ce3ae3d2b09ecc63144",
    backlog: true,
  },
  {
    slug: "congressgov-api-us",
    displayName: "Congress.gov API (US)",
    category: "recht",
    type: "live-signal",
    priority: "medium",
    access: "free-key",
    descriptionDe: "US-Bills nach Thema, Bipartisan-Score, Committee Activity als Policy-Signal.",
    descriptionEn: "US-Bills nach Thema, Bipartisan-Score, Committee Activity als Policy-Signal.",
    docUrl: "https://api.congress.gov",
    apiUrl: "https://api.congress.gov/v3",
    rateLimit: "5.000 Req/Stunde",
    notionUrl: "https://www.notion.so/1ba078bb6405469ea81afa4cc86ff1c5",
    needsKey: true,
  },
  {
    // IDMC was originally shipped as a live connector in Batch 5, but the
    // Phase-A smoke test revealed that every helix-tools-api.idmcdb.org
    // endpoint returns "Client is not registered." — IDMC requires a
    // client registration that we do not have. Demoted back to the
    // planned roadmap with needsKey: true.
    slug: "idmc-helix",
    displayName: "IDMC API (Internal Displacement)",
    category: "migration",
    type: "live-signal",
    priority: "medium",
    access: "free-signup",
    descriptionDe: "Binnenvertreibung weltweit (Konflikt + Disaster). Ergänzt UNHCR um Non-Refugee-Flüsse. Braucht Client-Registrierung bei IDMC Helix.",
    descriptionEn: "Internal displacement worldwide (conflict + disaster). Complements UNHCR with non-refugee flows. Requires client registration with IDMC Helix.",
    docUrl: "https://helix-tools-api.idmcdb.org/external-api/",
    apiUrl: "https://helix-tools-api.idmcdb.org/external-api/gidd/",
    notionUrl: "https://www.notion.so/1b39708d23e18007b4bffcf6cd3a6afe",
    needsKey: true,
  },
  {
    slug: "crunchbase",
    displayName: "Crunchbase API",
    category: "crypto",
    type: "live-signal",
    priority: "medium",
    access: "free-key",
    descriptionDe: "VC-Funding nach Sektor als Innovations-Frühindikator, Startup-Gründungen pro Quartal.",
    descriptionEn: "VC-Funding nach Sektor als Innovations-Frühindikator, Startup-Gründungen pro Quartal.",
    docUrl: "https://data.crunchbase.com/docs",
    apiUrl: "https://api.crunchbase.com/v4",
    rateLimit: "200 Req/Min (Free)",
    notionUrl: "https://www.notion.so/e94a493ef9da48ecb409cc562a1e8a47",
    backlog: true,
  },
  {
    slug: "ecdc-surveillance-atlas",
    displayName: "ECDC Surveillance Atlas",
    category: "gesundheit",
    type: "live-signal",
    priority: "medium",
    access: "no-auth",
    descriptionDe: "EU-Infektionskrankheiten-Trends — Influenza, AMR, Vaccine-Preventable Diseases.",
    descriptionEn: "EU-Infektionskrankheiten-Trends — Influenza, AMR, Vaccine-Preventable Diseases.",
    docUrl: "https://atlas.ecdc.europa.eu/public",
    notionUrl: "https://www.notion.so/5c876c167002406aa6fbdfafe15d3f0e",
  },
  {
    slug: "eia-api-us-energy",
    displayName: "EIA API (US Energy)",
    category: "energie",
    type: "live-signal",
    priority: "medium",
    access: "free-key",
    descriptionDe: "US-Öl-Lagerbestände (Weekly Petroleum Status Report = Marktmover), Stromerzeugungsmix, Erneuerbare.",
    descriptionEn: "US-Öl-Lagerbestände (Weekly Petroleum Status Report = Marktmover), Stromerzeugungsmix, Erneuerbare.",
    docUrl: "https://eia.gov/opendata",
    apiUrl: "https://api.eia.gov/v2",
    notionUrl: "https://www.notion.so/0335464f2cf7498c89ea88b370bb0f48",
    needsKey: true,
  },
  {
    slug: "ember-climate",
    displayName: "Ember Climate API",
    category: "energie",
    type: "live-signal",
    priority: "medium",
    access: "no-auth",
    descriptionDe: "Globaler Kohle-Ausstieg-Tracker, monatlicher Stromerzeugungsmix nach Land.",
    descriptionEn: "Globaler Kohle-Ausstieg-Tracker, monatlicher Stromerzeugungsmix nach Land.",
    docUrl: "https://ember-climate.org/data",
    apiUrl: "https://ember-climate.org/api",
    notionUrl: "https://www.notion.so/f7eb8a71723f4675b0f7e2ac30337486",
  },
  {
    slug: "eu-jrc-megatrends-hub",
    displayName: "EU JRC Megatrends Hub",
    category: "foresight",
    type: "forschung",
    priority: "medium",
    access: "no-auth",
    descriptionDe: "14 EU-Megatrends mit Evidenz-Links, Szenario-Beschreibungen und Policy-Implikationen. Strukturierter HTML-Zugriff möglich.",
    descriptionEn: "14 EU-Megatrends mit Evidenz-Links, Szenario-Beschreibungen und Policy-Implikationen. Strukturierter HTML-Zugriff möglich.",
    docUrl: "https://knowledge4policy.ec.europa.eu/foresight/tool/megatrends-hub_en",
    apiUrl: "https://knowledge4policy.ec.europa.eu/foresight/tool/megatrends-hub_en",
    rateLimit: "N/A (HTML)",
    notionUrl: "https://www.notion.so/4c5f6254f3dd46dc99f91bb015c1565d",
  },
  {
    // 2026-04-22 (Backlog: „ESPAS / EU JRC Quelle integrieren"): ESPAS ist
    // das EU-Foresight-Konsortium (Kommission + EP + Rat + EAD + Ausschüsse)
    // und publiziert langfristige Trend-Reports (Horizont 2030/2050). Keine
    // API — nur PDF-Publikationen. Daher als Referenzquelle / Foresight-
    // Dokument eingeordnet (backlog=true), um die Absicht festzuhalten,
    // ohne einen Connector zu versprechen, der technisch nicht baubar ist.
    slug: "espas-eu-foresight",
    displayName: "ESPAS (EU Foresight System)",
    category: "foresight",
    type: "forschung",
    priority: "medium",
    access: "download",
    descriptionDe: "Gemeinsames Foresight-Programm von EU-Kommission, EP, Rat und EAD. Publiziert strategische Lang-Trend-Reports (2030/2050) als PDF. Für SIS als Referenzquelle und LLM-Kontext nutzbar, keine Live-API.",
    descriptionEn: "Joint foresight programme of the European Commission, Parliament, Council and EEAS. Publishes long-horizon (2030/2050) trend reports as PDF. For SIS usable as a reference source and LLM context, no live API.",
    docUrl: "https://espas.eu/",
    apiUrl: "https://espas.eu/",
    rateLimit: "N/A (PDF)",
    notionUrl: "https://www.notion.so/33661c848a4f819e8ed4dc0a894aa73c",
    backlog: true,
  },
  {
    slug: "gesis-eurobarometer-datenzugang",
    displayName: "GESIS / Eurobarometer Datenzugang",
    category: "umfragen",
    type: "forschung",
    priority: "medium",
    access: "download",
    descriptionDe: "Eurobarometer-Umfragedaten seit 1973: EU-Bürger-Einstellungen zu Politik, Wirtschaft, Gesellschaft. EU-Pendant zum WVS.",
    descriptionEn: "Eurobarometer-Umfragedaten seit 1973: EU-Bürger-Einstellungen zu Politik, Wirtschaft, Gesellschaft. EU-Pendant zum WVS.",
    docUrl: "https://www.gesis.org/en/eurobarometer-data-service/home",
    apiUrl: "https://search.gesis.org/research_data?topic=Eurobarometer",
    rateLimit: "N/A (Datei-Download)",
    notionUrl: "https://www.notion.so/7c0d844aa822490c8158c7927c9f54fd",
    backlog: true,
  },
  {
    slug: "igdb-api-internet-game-database",
    displayName: "IGDB API (Internet Game Database)",
    category: "gaming",
    type: "live-signal",
    priority: "medium",
    access: "free-signup",
    descriptionDe: "PopScore-Primitives für Echtzeit-Gaming-Trends. Genre/Themen-Analyse über Release-Daten.",
    descriptionEn: "PopScore-Primitives für Echtzeit-Gaming-Trends. Genre/Themen-Analyse über Release-Daten.",
    docUrl: "https://api-docs.igdb.com",
    apiUrl: "https://api.igdb.com/v4",
    notionUrl: "https://www.notion.so/459792e574d24727b17af061df71c961",
    needsKey: true,
  },
  {
    slug: "indeed-hiring-lab",
    displayName: "Indeed Hiring Lab",
    category: "arbeit",
    type: "live-signal",
    priority: "medium",
    access: "public-scrape",
    descriptionDe: "Job-Posting-Trends nach Land, Branche, Skill — Strukturwandel-Frühindikator.",
    descriptionEn: "Job-Posting-Trends nach Land, Branche, Skill — Strukturwandel-Frühindikator.",
    docUrl: "https://hiringlab.org/data",
    notionUrl: "https://www.notion.so/7d0fce1bf68548a4838d7cf09cfbbe14",
    backlog: true,
  },
  {
    slug: "ioda-internet-outage-detection",
    displayName: "IODA (Internet Outage Detection)",
    category: "cyber",
    type: "live-signal",
    priority: "medium",
    access: "no-auth",
    descriptionDe: "Internet-Shutdowns als Krisen-/Zensur-Signal. Korreliert mit ACLED-Protesten.",
    descriptionEn: "Internet-Shutdowns als Krisen-/Zensur-Signal. Korreliert mit ACLED-Protesten.",
    docUrl: "https://ioda.inetintel.cc.gatech.edu",
    notionUrl: "https://www.notion.so/11c1c44c653c42858e7df0a1af9d04bb",
    backlog: true,
  },
  {
    slug: "listen-notes-api-podcasts",
    displayName: "Listen Notes API (Podcasts)",
    category: "publishing",
    type: "social",
    priority: "medium",
    access: "free-key",
    descriptionDe: "Podcast-Suchmaschine, 3M+ Podcasts. Themen-Trends, Genre-Wachstum.",
    descriptionEn: "Podcast-Suchmaschine, 3M+ Podcasts. Themen-Trends, Genre-Wachstum.",
    docUrl: "https://listennotes.com/api/docs",
    apiUrl: "https://listen-api.listennotes.com/api/v2",
    rateLimit: "5 Req/Min, 300/Monat (Free)",
    notionUrl: "https://www.notion.so/0a7a10a4a6fc45c685ea1ce7cd44ae0d",
    needsKey: true,
  },
  {
    slug: "pew-research-center-dataset-downloads",
    displayName: "Pew Research Center — Dataset Downloads",
    category: "umfragen",
    type: "forschung",
    priority: "medium",
    access: "download",
    descriptionDe: "Gesellschaftliche Einstellungen, Religionstrends, Mediennutzung, politische Polarisierung in den USA und global.",
    descriptionEn: "Gesellschaftliche Einstellungen, Religionstrends, Mediennutzung, politische Polarisierung in den USA und global.",
    docUrl: "https://www.pewresearch.org/download-datasets/",
    apiUrl: "https://www.pewresearch.org/download-datasets/",
    rateLimit: "N/A (Datei-Download)",
    notionUrl: "https://www.notion.so/01407c13c91f4481b6d24b810e09907c",
    backlog: true,
  },
  {
    slug: "shodan",
    displayName: "Shodan API",
    category: "cyber",
    type: "live-signal",
    priority: "medium",
    access: "free-signup",
    descriptionDe: "Internet-Scan — exposed Devices, IoT-Sicherheitslage, industrielle Kontrollsysteme pro Land.",
    descriptionEn: "Internet-Scan — exposed Devices, IoT-Sicherheitslage, industrielle Kontrollsysteme pro Land.",
    docUrl: "https://developer.shodan.io/api",
    apiUrl: "https://api.shodan.io",
    notionUrl: "https://www.notion.so/3e2219cd509d4f46b168db068a40d5e6",
    needsKey: true,
  },
  {
    slug: "spotify-web",
    displayName: "Spotify Web API",
    category: "kultur",
    type: "live-signal",
    priority: "medium",
    access: "free-signup",
    descriptionDe: "Audio Features (Valence/Energy/Danceability) als Stimmungsindex. Top Artists/Tracks nach Zeitraum.",
    descriptionEn: "Audio Features (Valence/Energy/Danceability) als Stimmungsindex. Top Artists/Tracks nach Zeitraum.",
    docUrl: "https://developer.spotify.com/documentation/web-api",
    apiUrl: "https://api.spotify.com/v1",
    notionUrl: "https://www.notion.so/c24e55279f8d419bb3bc2e2ea1886b95",
    backlog: true,
  },
  {
    slug: "tomtom-traffic-index",
    displayName: "TomTom Traffic Index API",
    category: "mobilitaet",
    type: "live-signal",
    priority: "medium",
    access: "free-key",
    descriptionDe: "Stau-Index pro Stadt als Wirtschaftsaktivitäts-Proxy. 400+ Städte.",
    descriptionEn: "Stau-Index pro Stadt als Wirtschaftsaktivitäts-Proxy. 400+ Städte.",
    docUrl: "https://developer.tomtom.com/traffic-api",
    apiUrl: "https://api.tomtom.com/traffic",
    rateLimit: "2.500 Transaktionen/Tag (Free)",
    notionUrl: "https://www.notion.so/8e1a028a0e2a46ffba56ba7004a63eed",
    needsKey: true,
  },
  {
    slug: "wfp-vam-nahrungsmittelpreise",
    displayName: "WFP VAM (Nahrungsmittelpreise)",
    category: "agrar",
    type: "live-signal",
    priority: "medium",
    access: "no-auth",
    descriptionDe: "Echtzeit-Nahrungsmittelpreise in Krisenregionen. Vulnerability Analysis & Mapping.",
    descriptionEn: "Echtzeit-Nahrungsmittelpreise in Krisenregionen. Vulnerability Analysis & Mapping.",
    docUrl: "https://dataviz.vam.wfp.org",
    apiUrl: "https://api.vam.wfp.org",
    notionUrl: "https://www.notion.so/5e35f914b9af47cc941ace1125c3b23a",
  },
  {
    slug: "world-values-survey-wvs-daten-download",
    displayName: "World Values Survey (WVS) — Daten-Download",
    category: "umfragen",
    type: "forschung",
    priority: "medium",
    access: "download",
    descriptionDe: "Weltweit wichtigste Längsschnitt-Wertestudie (120+ Länder, seit 1981, Wave 8 läuft 2024–2026). Basis für Values-Ebene im STEEP+V-Modell.",
    descriptionEn: "Weltweit wichtigste Längsschnitt-Wertestudie (120+ Länder, seit 1981, Wave 8 läuft 2024–2026). Basis für Values-Ebene im STEEP+V-Modell.",
    docUrl: "https://www.worldvaluessurvey.org/WVSDocumentationWVL.jsp",
    apiUrl: "https://www.worldvaluessurvey.org/WVSDocumentationWVL.jsp",
    rateLimit: "N/A (Datei-Download)",
    notionUrl: "https://www.notion.so/b299bf360a7343668be3cff3bba30f34",
    backlog: true,
  },
  {
    slug: "alpha-vantage",
    displayName: "Alpha Vantage API",
    category: "makro",
    type: "live-signal",
    priority: "low",
    access: "free-key",
    descriptionDe: "Aktien-, Devisen- und Kryptowährungsdaten. Ergänzt Finnhub mit Makro-Wirtschafts-Endpunkten (CPI, GDP, Inflation).",
    descriptionEn: "Aktien-, Devisen- und Kryptowährungsdaten. Ergänzt Finnhub mit Makro-Wirtschafts-Endpunkten (CPI, GDP, Inflation).",
    docUrl: "https://www.alphavantage.co/documentation/",
    apiUrl: "https://www.alphavantage.co/query",
    rateLimit: "25 Calls/Tag (Free), 500/Tag mit Key",
    notionUrl: "https://www.notion.so/84c8d5c8a6484064bc2e3877cba9090b",
    needsKey: true,
  },
  {
    slug: "copernicus-data-space-ecosystem",
    displayName: "Copernicus Data Space Ecosystem API",
    category: "klima",
    type: "live-signal",
    priority: "low",
    access: "free-signup",
    descriptionDe: "Satellitendaten (Sentinel-1/2/3) für Klima-Monitoring, Landnutzung, Katastrophen-Mapping.",
    descriptionEn: "Satellitendaten (Sentinel-1/2/3) für Klima-Monitoring, Landnutzung, Katastrophen-Mapping.",
    docUrl: "https://dataspace.copernicus.eu/analyse/apis",
    apiUrl: "https://sh.dataspace.copernicus.eu/api/v1/process",
    rateLimit: "300 Processing Units/Monat (Free)",
    notionUrl: "https://www.notion.so/14c38614d38b4a668be90597999a42bb",
    backlog: true,
  },
  {
    slug: "layoffsfyi-tech-layoff-tracker",
    displayName: "Layoffs.fyi (Tech-Layoff-Tracker)",
    category: "arbeit",
    type: "live-signal",
    priority: "low",
    access: "public-scrape",
    descriptionDe: "Tech-Layoff-Wellen als Disruptions-Signal. Sektorale Muster erkennbar.",
    descriptionEn: "Tech-Layoff-Wellen als Disruptions-Signal. Sektorale Muster erkennbar.",
    docUrl: "https://layoffs.fyi",
    notionUrl: "https://www.notion.so/684994fa35104b84a6dd86edd2db591f",
    backlog: true,
  },
  {
    slug: "millennium-project-15-global-challenges",
    displayName: "Millennium Project — 15 Global Challenges",
    category: "foresight",
    type: "forschung",
    priority: "low",
    access: "no-auth",
    descriptionDe: "Kontinuierliches Foresight-Programm seit 1996, jährlich durch 4.000+ Experten via Delphi aktualisiert. Komplementär zu SIS-Szenario-Modell.",
    descriptionEn: "Kontinuierliches Foresight-Programm seit 1996, jährlich durch 4.000+ Experten via Delphi aktualisiert. Komplementär zu SIS-Szenario-Modell.",
    docUrl: "https://www.millennium-project.org/challenges-overview/",
    apiUrl: "https://www.millennium-project.org/challenges-overview/",
    rateLimit: "N/A (HTML)",
    notionUrl: "https://www.notion.so/b514fffa0d5a4a1888bfa4ba2b0b32cb",
    backlog: true,
  },
  {
    slug: "noaa-climate-data-online",
    displayName: "NOAA Climate Data Online API",
    category: "klima",
    type: "live-signal",
    priority: "low",
    access: "free-key",
    descriptionDe: "US-Klimadaten + globale Wetterstation-Messungen. Ergänzt NASA EONET für klimatische Extremereignisse.",
    descriptionEn: "US-Klimadaten + globale Wetterstation-Messungen. Ergänzt NASA EONET für klimatische Extremereignisse.",
    docUrl: "https://www.ncei.noaa.gov/cdo-web/webservices/v2",
    apiUrl: "https://www.ncei.noaa.gov/cdo-web/api/v2/data",
    rateLimit: "1.000 Calls/Tag, 5 Calls/Sek",
    notionUrl: "https://www.notion.so/3d5e10747ccd42dab5480157ded2cfad",
    needsKey: true,
  },
  {
    slug: "openstreetmap-overpass",
    displayName: "OpenStreetMap Overpass API",
    category: "mobilitaet",
    type: "live-signal",
    priority: "low",
    access: "no-auth",
    descriptionDe: "Urbane Veränderungen trackbar — neue Straßen, Gebäude, Infrastruktur als Entwicklungs-Signal.",
    descriptionEn: "Urbane Veränderungen trackbar — neue Straßen, Gebäude, Infrastruktur als Entwicklungs-Signal.",
    docUrl: "https://wiki.openstreetmap.org/wiki/Overpass_API",
    apiUrl: "https://overpass-api.de/api/interpreter",
    notionUrl: "https://www.notion.so/90efa31dd517494c9adb98a2dc5b2438",
  },
  {
    slug: "parltrack-eu-parlament",
    displayName: "Parltrack (EU-Parlament)",
    category: "recht",
    type: "live-signal",
    priority: "low",
    access: "open-source",
    descriptionDe: "EU-Parlament — Abstimmungsverhalten, Amendments, Lobbying-Register.",
    descriptionEn: "EU-Parlament — Abstimmungsverhalten, Amendments, Lobbying-Register.",
    docUrl: "https://parltrack.org",
    notionUrl: "https://www.notion.so/e23ab82d15cd486981fd0cde6858e5d5",
    backlog: true,
  },

  // ── Batch-6 (2026-04): World Monitor Expansion + neue Quellen ────────
  {
    slug: "bis-data",
    displayName: "BIS Data API (Zentralbank-Raten)",
    category: "makro",
    type: "forschung",
    priority: "high",
    access: "no-auth",
    descriptionDe: "Zentralbank-Leitzinsen aller Länder, REER, Kredit-Volumen. Monetäre Policy als Wirtschaftssignal.",
    descriptionEn: "Central bank policy rates, REER, credit volume. Monetary policy as economic signal.",
    docUrl: "https://bis.org/statistics/full_data_sets.htm",
    apiUrl: "https://data.bis.org/api/v2",
    notionUrl: "https://www.notion.so/775f6f9637a44e419fb113c6efdb82f4",
    needsKey: false,
  },
  {
    slug: "abuse-ch",
    displayName: "abuse.ch Threat Feeds",
    category: "cyber",
    type: "live-signal",
    priority: "high",
    access: "no-auth",
    descriptionDe: "Malware-URLs, C2-Server, IoCs in Echtzeit. Volumen-Spikes = aktive Cyber-Kampagnen.",
    descriptionEn: "Malware URLs, C2 servers, IoCs in real time. Volume spikes = active cyber campaigns.",
    docUrl: "https://urlhaus-api.abuse.ch",
    apiUrl: "https://urlhaus-api.abuse.ch/v1",
    notionUrl: "https://www.notion.so/c997d8b6e6184d9db230f3944e4686ad",
    needsKey: false,
  },
  {
    slug: "adsb-lol",
    displayName: "adsb.lol API (Flugverkehr / Militär)",
    category: "mobilitaet",
    type: "live-signal",
    priority: "high",
    access: "no-auth",
    descriptionDe: "Militärische Flugbewegungen als Eskalations-Signal, Cargo-Volumen als Wirtschaftsindikator.",
    descriptionEn: "Military flight movements as escalation signal, cargo volume as economic indicator.",
    docUrl: "https://api.adsb.lol",
    apiUrl: "https://api.adsb.lol/v2/mil",
    notionUrl: "https://www.notion.so/ba475bf16bdc41378b7e5cc929309347",
    needsKey: false,
  },
  {
    slug: "uk-fcdo-travel",
    displayName: "UK FCDO Travel Advisories",
    category: "geopolitik",
    type: "live-signal",
    priority: "high",
    access: "no-auth",
    descriptionDe: "Reisewarnungen pro Land als Geopolitik-Signal. Stufenänderungen = Eskalations-/Deeskalations-Frühindikator.",
    descriptionEn: "Travel advisories per country as geopolitics signal. Level changes = escalation/de-escalation early indicator.",
    docUrl: "https://www.gov.uk/api",
    apiUrl: "https://www.gov.uk/api/content/foreign-travel-advice",
    notionUrl: "https://www.notion.so/3b03c68b04c54e5da07505029018d596",
    needsKey: false,
  },
  {
    slug: "aisstream",
    displayName: "aisstream.io (Schiffstracking / AIS)",
    category: "supply",
    type: "live-signal",
    priority: "medium",
    access: "free-key",
    descriptionDe: "Echtzeit-Schiffspositionen, Hafenauslastung, Routen-Anomalien (Suez-Umfahrung = Krise).",
    descriptionEn: "Real-time ship positions, port utilisation, route anomalies (Suez rerouting = crisis).",
    docUrl: "https://aisstream.io/documentation",
    apiUrl: "https://aisstream.io",
    notionUrl: "https://www.notion.so/9eaa4540019e42ba9da4f5b65911a037",
    needsKey: true,
  },
  {
    slug: "telegeography-cables",
    displayName: "TeleGeography Submarine Cable Map",
    category: "cyber",
    type: "forschung",
    priority: "medium",
    access: "open-source",
    descriptionDe: "Untersee-Kabelrouten als Cyber-Verwundbarkeits-Layer. Kabelschnitte = Internet-Ausfälle + Geopolitik-Signal.",
    descriptionEn: "Submarine cable routes as cyber-vulnerability layer. Cable cuts = internet outages + geopolitics signal.",
    docUrl: "https://github.com/telegeography/www.submarinecablemap.com",
    notionUrl: "https://www.notion.so/7600e98703e443ac86c88fded4dba636",
    backlog: true,
  },
  {
    slug: "opensky-network",
    displayName: "OpenSky Network API (Flugtracking)",
    category: "mobilitaet",
    type: "live-signal",
    priority: "low",
    access: "free-signup",
    descriptionDe: "Open-Source Flugtracking. Akademisch nutzbar. Ergänzung zu adsb.lol mit historischen Daten.",
    descriptionEn: "Open-source flight tracking. Academic use. Complements adsb.lol with historical data.",
    docUrl: "https://openskynetwork.github.io/opensky-api",
    apiUrl: "https://opensky-network.org/api",
    notionUrl: "https://www.notion.so/1acaa7b646d841d8bd84f0da50d50772",
    backlog: true,
  },
  {
    slug: "global-energy-monitor",
    displayName: "Global Energy Monitor — Pipeline Tracker",
    category: "energie",
    type: "forschung",
    priority: "medium",
    access: "open-source",
    descriptionDe: "Gas/Öl-Pipelines weltweit als Energie-Geopolitik-Layer (Nord Stream, TAP, etc.). CC BY 4.0.",
    descriptionEn: "Global gas/oil pipelines as energy geopolitics layer (Nord Stream, TAP, etc.). CC BY 4.0.",
    docUrl: "https://globalenergymonitor.org/projects/global-gas-infrastructure-tracker",
    notionUrl: "https://www.notion.so/363cb02c5e4d48b093d19ebcdadde56d",
    backlog: true,
  },
  {
    slug: "planetary-computer",
    displayName: "Microsoft Planetary Computer (STAC API)",
    category: "klima",
    type: "forschung",
    priority: "medium",
    access: "no-auth",
    descriptionDe: "Sentinel-2 (Landnutzung), Sentinel-5P (Luftqualität), Landsat. Bildgebende Satellitendaten.",
    descriptionEn: "Sentinel-2 (land use), Sentinel-5P (air quality), Landsat. Satellite imagery data.",
    docUrl: "https://planetarycomputer.microsoft.com/docs",
    apiUrl: "https://planetarycomputer.microsoft.com/api/stac/v1",
    notionUrl: "https://www.notion.so/af6362b752cb4e329745e58d6be9c0ac",
    backlog: true,
  },
  {
    slug: "global-fishing-watch",
    displayName: "Global Fishing Watch (Dark Vessels / AIS)",
    category: "supply",
    type: "live-signal",
    priority: "low",
    access: "free-signup",
    descriptionDe: "Schiffe die AIS abschalten als Sanctions-Evasion-Signal. Dark Vessel Detection für Geopolitik.",
    descriptionEn: "Ships disabling AIS as sanctions evasion signal. Dark vessel detection for geopolitics.",
    docUrl: "https://globalfishingwatch.org/our-apis",
    apiUrl: "https://gateway.api.globalfishingwatch.org/v3",
    notionUrl: "https://www.notion.so/98d59e0113d34d319e6a9b0d738c19eb",
    backlog: true,
  },
];

/** Category key → German + English label, for QuellenTable filter pills. */
export const PLANNED_CATEGORY_LABELS: Record<PlannedConnectorCategory, { de: string; en: string }> = {
  agrar: { de: "Nahrungsmittel & Agrar", en: "Food & Agriculture" },
  arbeit: { de: "Arbeitsmarkt", en: "Labor Market" },
  crypto: { de: "Finanzen & Crypto", en: "Finance & Crypto" },
  cyber: { de: "Cybersecurity", en: "Cybersecurity" },
  energie: { de: "Energie & Rohstoffe", en: "Energy & Commodities" },
  foresight: { de: "Foresight & Szenarien", en: "Foresight & Scenarios" },
  gaming: { de: "Gaming", en: "Gaming" },
  geopolitik: { de: "Geopolitik", en: "Geopolitics" },
  gesellschaft: { de: "Gesellschaft", en: "Society" },
  gesundheit: { de: "Gesundheit", en: "Health" },
  klima: { de: "Klima & Umwelt", en: "Climate & Environment" },
  kultur: { de: "Kultur & Entertainment", en: "Culture & Entertainment" },
  makro: { de: "Makroökonomie", en: "Macroeconomics" },
  migration: { de: "Migration", en: "Migration" },
  mobilitaet: { de: "Mobilität & Urbanisierung", en: "Mobility & Urbanisation" },
  news: { de: "News & Medien", en: "News & Media" },
  prognose: { de: "Prognosemärkte", en: "Prediction Markets" },
  publishing: { de: "Publishing & Podcasts", en: "Publishing & Podcasts" },
  recht: { de: "Gesetzgebung & Regulierung", en: "Legislation & Regulation" },
  supply: { de: "Supply Chain & Handel", en: "Supply Chain & Trade" },
  tech: { de: "Tech & Developer", en: "Tech & Developers" },
  umfragen: { de: "Umfragen & Meinungsforschung", en: "Surveys & Opinion Research" },
  wetten: { de: "Wettmärkte", en: "Betting Markets" },
  wissenschaft: { de: "Wissenschaft", en: "Science" },
};

/** Access enum → German + English human label. */
export const ACCESS_LABELS: Record<PlannedConnectorAccess, { de: string; en: string }> = {
  "no-auth":       { de: "Kein Auth",                en: "No auth" },
  "free-key":      { de: "Kostenloser Key",          en: "Free key" },
  "free-signup":   { de: "Kostenlose Registrierung", en: "Free signup" },
  "download":      { de: "Download",                 en: "Download" },
  "commercial":    { de: "Kommerziell",              en: "Commercial" },
  "open-source":   { de: "Open Source",              en: "Open source" },
  "public-scrape": { de: "Scrapeable",               en: "Scrapeable" },
};
